config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'splash#index'

  resources :categories do
    resources :records
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    # user ||= User.new # guest user (not logged in)
    can :manage, Category, user: user
    can :manage, Record, user: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_record.rb
class CategoriesRecord < ApplicationRecord
  belongs_to :record
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :categories_records, dependent: :destroy
  has_many :records, through: :categories_records
  has_one_attached :icon

  validates :name, presence: true
  validates :user, presence: true

  def first_three_transactions
    records.limit(3)
  end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :categories_records, dependent: :destroy
  has_many :categories, through: :categories_records

  validates :name, presence: true
  validates :ammount, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :records

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  # before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    # @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # def set_category
  #   @category = Category.find(params[:id])
  # end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :category
  load_and_authorize_resource :record, through: :category, except: %i[create new]
  # before_action :set_record, only: %i[show edit update destroy]
  skip_before_action :verify_authenticity_token

  # GET /records or /records.json
  def index; end

  # GET /records/1 or /records/1.json
  def show; end

  # GET /records/new
  def new
    @record = Record.new
    @category = Category.find(params[:category_id])
  end

  # GET /records/1/edit
  def edit; end

  # POST /records or /records.json
  def create
    authorize! :manage, @category
    @record = current_user.records.new(record_params)
    cat_ids = create_params[:categories][:ids].slice(1..-1) || []
    categories = current_user.categories.find(cat_ids)
    @record.categories = categories

    respond_to do |format|
      if @record.save
        format.html { redirect_to category_records_path(@category), notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to [@category, @record], notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy

    respond_to do |format|
      format.html { redirect_to category_records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def record_params
    params.require(:record).permit(:name, :ammount)
  end

  def create_params
    params.require(:record).permit(:name, :ammount, categories: [ids: []])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
require 'pathname'

module ApplicationHelper
  def render_header
    original_url = request.original_url
    back = Pathname.new(original_url).parent.to_s
    render partial: 'shared/header', locals: {
      title: params[:controller].upcase,
      back: back
    }
  end

  def link2(*args, **kwargs)
    if block_given?
      link_to(*args, **kwargs) do
        '<code></code>'
      end
    else
      link_to(*args, **kwargs)
    end
  end

  def link(body, *args, **kwargs)
    raise ArgumentError.new, '\'link\' method does not take a block' if block_given?

    link_to(*args, **kwargs) do
      content_tag(:div, class: 'link') do
        body
      end
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/categories/_category.html.erb
<div class="category-box">
  <div class="category">
    <% if category.icon.attached? %>
      <%= image_tag category.icon, class: 'icon' %>
    <% end %>
    <div class="text">
      <h3><%= category.name %></h3>
      <p><%= category.created_at.to_formatted_s(:short) %></p>
    </div>
    <strong><p class="price">$<%= category.records.sum(:ammount)  %> </p></strong>
  </div>
  <% if category.records.count.positive? %>
    <ul class="records">
      <% render category.first_three_transactions, layout: 'box' %>
    </ul>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link "Show this category", @category %>
  <%= link "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="categories">
  <% @categories.each do |category| %>
    <%= link_to category_records_path(category) do %>
      <%= render category %>
    <% end %>
  <% end %>
</div>

<%= link "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to category_records_path(@category), class: 'category', id: (dom_id @category) do %>
  <%= render @category %>
<% end %>

<div>
  <%= link "Edit this category", edit_category_path(@category) %>
  <%= link "View Transactions", category_records_path(@category) %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
     <script src="https://kit.fontawesome.com/29d7bf5b00.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render_header %>
    <div>
      <% flash.each do |name, msg| -%>
        <%= content_tag :span, msg, class: name %>
      <% end -%>
    </div>
    <main id="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with(model: [@category, record]) do |form| %>
  <% if record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :ammount, style: "display: block" %>
    <%= form.number_field :ammount %>
  </div>

  <div>
    <%= form.fields_for :categories do |f| %>
      <%= f.collection_check_boxes  :ids, current_user.categories, :id, :name %>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/records/_record.html.erb
<div class='record' >
  <p>
    <strong>Name:</strong>
    <%= record.name %>
  </p>

  <p>
    <strong>Ammount:</strong>
    <%= record.ammount %>
  </p>

</div>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render "form", record: @record %>

<br>

<div>
  <%= link "Show this record", [@category, @record] %>
  <%= link "Back to records", category_records_path(@category) %>
</div>

app/views/records/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Records</h1>

<div class="records">
  <% @records.each do |record| %>
    <%= link_to [@category, record] do %>
      <%= render record %>
    <% end %>
  <% end %>
</div>

<div>
  <%= link "New record", new_category_record_path(@category) %>
</div>
<div>
  <%= link "Back to Categories", categories_path %>
</div>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render "form", record: @record %>

<br>

<div>
  <%= link "Back to records", category_records_path(@category) %>
</div>

app/views/records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @record %>

<div>
  <%= link "Edit this record", edit_category_record_path(@category, @record) %>
  <%= link "Back to records", category_records_path(@category) %>

  <%= button_to "Destroy this record", [@category, @record], method: :delete %>
</div>

app/views/shared/_header.html.erb
<header>
  <% if back %>
    <%= link_to :back do %>
      <i class="icon fas fa-chevron-left"></i>
    <% end %>
  <% else %>
    <i class="icon fas fa-bars"></i>
  <% end %>
  <h1><%= title %></h1>
  <i class="icon fas fa-search"></i>
</header>

app/views/splash/index.html.erb
<main>
  <h1>Budget App</h1>
  <div>
    <%= button_to 'LOG IN', new_user_session_url, method: :get %>
    <%= button_to 'SIGN UP', new_user_registration_url, method: :get %>
  </div>
</main>